Translate Nodejs Course, fixes #100
rolling-scopes-school/docs pull request #106
Opened 2020-03-01 12:33 UTC by xmelsky

Translate Nodejs Course, fixes #100

2020-03-02 15:52 UTC, Shastel submitted a review, later dismissed

2020-03-02 15:52 UTC, Shastel commented on docs/en/nodejs-course.md
> +The course duration is 5 weeks. For self study you'll need from 8 hrs per week.
```suggestion
The course duration is 5 weeks. For self-study, you'll need at least 8 hrs per week.
```

2020-03-16 17:36 UTC, Munishkin requested changes
I just left some minor comments regarding the text. I hope that is okie with you too.

2020-03-16 17:36 UTC, Munishkin commented on docs/en/nodejs-course.md
> +During the course progress you'll need to create a CLI application for NodeJS and also a REST server.
During the course you'll need to create a CLI application for NodeJS and a REST server.

2020-03-16 17:36 UTC, Munishkin commented on docs/en/nodejs-course.md
> +In the course will be covered next topics:
The next topics will be covered in the course:

2020-03-16 17:36 UTC, Munishkin commented on docs/en/nodejs-course.md
> +- NodeJS basics, its architechture,environment variables, specifics of working with asynchronious code, interaction with the file system, working with Streams.
NodeJS basics, its architecture, environment variables, specifics of working with asynchronous code, interaction with the file system, working with streams.

2020-03-16 17:36 UTC, Munishkin commented on docs/en/nodejs-course.md
> +- Architectural patterns being used during application design process.
Architectural patterns used during application design process.

2020-03-16 17:36 UTC, Munishkin commented on docs/en/nodejs-course.md
> +- Configuration, logging and errors handling.
error handling.

2020-03-17 12:40 UTC, Munishkin approved these changes

2020-03-17 13:11 UTC, Munishkin reviewed
Я пропустила этот файл. Хоть здесь текст на русском языке, я все же решила прочитать. Мои комментарии могут быть ошибочными.

2020-03-17 13:11 UTC, Munishkin commented on docs/rs-school-trainer.md
> +- На каждом занятии уделять не более 2 часа теории. Теоретические знания должны быть покрыты практикой - рабочий пример кода, таск, тест или другая активность. Все, что не закреплено практикой, быстр
На каждом занятии уделять не более двух часов на теоретическую часть.

2020-03-17 13:11 UTC, Munishkin commented on docs/rs-school-trainer.md
> +- Во время оффлайн занятий общаться со всей аудиторией, а не только с первыми рядами
Во время оффлайн занятий общаться со всей аудиторией, а не только со слушателями первых рядов.

2020-03-17 13:11 UTC, Munishkin commented on docs/rs-school-trainer.md
> +- Если тренер проводит цикл занятий, перед началом нового также стоит потратить время на Q & A по теме предыдущего занятия
Если тренер проводит цикл занятий, перед началом нового, также стоит потратить время на Q & A по теме предыдущего занятия.
я не уверена по поводу запятых, но чисто по ощущениям кажется запятая нужна

2020-03-17 13:11 UTC, Munishkin commented on docs/rs-school-trainer.md
> +- Желательно разделить занятие на несколько блоков, после каждого из которых уделить время на ответы на вопросы студентов.
Желательно разделить занятие на несколько блоков, после каждого из которых, уделить время на ответы и на вопросы студентов.
я не уверена по поводу запятых, но чисто по ощущениям кажется запятая нужна

2020-03-17 15:35 UTC, xmelsky commented
> Я пропустила этот файл. Хоть здесь текст на русском языке, я все же решила прочитать. Мои комментарии могут быть ошибочными.

Этот файл был лишним, я случайно подтянул изменения из mater. sorry )
Сделал reset и force update.

2020-03-18 13:36 UTC, Munishkin approved these changes

2020-03-18 13:38 UTC, Munishkin approved these changes

2020-03-18 13:41 UTC, Munishkin approved these changes

2020-03-18 13:55 UTC, merged