docs: eng translation on fix-typo
rolling-scopes-school/docs pull request #114
Opened 2020-04-03 01:53 UTC by FrostyDog

Add english tranlsation of fix-typo.md

2020-04-08 08:26 UTC, ghost requested changes

2020-04-08 08:26 UTC, ipelekhan commented on docs/en/fix-typo.md
> +
Пустые строки.

2020-04-08 08:26 UTC, ipelekhan commented on docs/en/fix-typo.md
> +Keep track of your pull request. What people will comment on, what the maintainer will say, whether or not the edits you proposed will accept.
```suggestion
Keep track of your pull request. What people will comment on, what the maintainer will say, whether or not the edits you have proposed will be accepted.
```

2020-04-08 08:26 UTC, ipelekhan commented on docs/en/fix-typo.md
> +### 5. Add changes to your own repository copy
Может быть стоит поменять `repository copy` на `fork`? Хотя наверное для новичком первое будет понятнее, несмотря на то что второе соответствует терминологии git/Github.

2020-04-08 08:26 UTC, ipelekhan commented on docs/en/fix-typo.md
> +Suppose our branch is called fix-typo.
```suggestion
Suppose our branch is called `fix-typo`.
```

Чтобы выделить название ветки.

2020-04-08 13:26 UTC, FrostyDog commented on docs/en/fix-typo.md
> +### 5. Add changes to your own repository copy
> Может быть стоит поменять `repository copy` на `fork`? Хотя наверное для новичком первое будет понятнее, несмотря на то что второе соответствует терминологии git/Github.

Ну - как в оригинале - так и мы. Да и я fork скорее как глагол восприниимаю. Repository copy будет проще и понятнее - предлагаю оставить.

2020-04-08 19:16 UTC, ghost approved these changes

2020-04-08 19:19 UTC, rootical approved these changes

2020-04-08 19:19 UTC, rootical commented on docs/en/fix-typo.md
> +Documentation repository link: https://github.com/rolling-scopes-school/docs
@dzmitry-varabei  will it be `docs/en`?

2020-04-10 10:03 UTC, dzmitry-varabei commented on docs/en/fix-typo.md
> +Documentation repository link: https://github.com/rolling-scopes-school/docs
it will be https://docs.rs.school/#/en/

2020-04-10 10:04 UTC, merged