Streaming doc
rolling-scopes-school/docs pull request #12
Opened 2019-04-03 09:36 UTC by davojta

2019-04-03 15:31 UTC, humanamburu approved these changes

2019-04-07 18:01 UTC, davojta commented
@dzmitry-varabei как тебе ?

2019-04-07 18:06 UTC, dzmitry-varabei commented
По контенту всё огонь! Спасибо, Денис!Думаю оформление чуть поправить и буду мержить

On Apr 7, 2019, at 20:01, Dzianis Sheka <notifications@github.com<mailto:notifications@github.com>> wrote:


@dzmitry-varabei<https://github.com/dzmitry-varabei> как тебе ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/rolling-scopes-school/docs/pull/12#issuecomment-480614817>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ACUS8MAweAbAKqLDcm9e8Jvw9oOo2v9fks5vejJrgaJpZM4caDwp>.

2019-04-08 08:10 UTC, dzmitry-varabei commented
@Shastel Максим, добавь плиз информацию по тамбнейлам. Может еще что-то надо?

2019-04-10 14:22 UTC, Shastel requested changes
Пожалуйста обнови .gitignore

2019-04-10 18:43 UTC, davojta commented
О, оказывается на маке всякие доп служебные файлы есть ) Завтра обновлю )

2019-04-18 07:42 UTC, merged