docs: add translation  for stage1.md  and rs-school-chats.md
rolling-scopes-school/docs pull request #132
Opened 2020-05-13 09:48 UTC by valentintur

2020-05-16 09:03 UTC, Munishkin requested changes
Please, follow my comments to improve the translation.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +* The channel discusses only the topics indicated in its name, for example, **#live-coding** is intended __exclusively__ for discussions of live streams. Non-topic posts will be deleted. The channel
You can discuss only the topics indicated in channel's name, for example, **#live-coding** is intended __exclusively__ for discussions of live streams. Unrelated posts will be deleted. The channel categories are explained further.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +* It is advisable to respond to a person through mention (@nicknamehere).
It is a good practice to respond to a person by mentioning their nickname (@nicknamehere).

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +2. For each student enrollment, a separate category in Discord. For example, for the set `RSSchool 2019Q1` - ` RS2019Q1`
There is a separate category for each student cohort in Discord. For example, for the cohort `RSSchool 2019Q1` - ` RS2019Q1`

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +3. The category is created along with the start of the set.
The category is created at the start of class.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +5. For each channel in the category is registered - channel topic containing information about the channel
Each channel in the category has a channel topic which contains information about the channel

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +The format of the category is `RSYYYYQQ`, where YYYY is the year of launch, and QQ is the quarter of the start, for example, winter (Q1) or autumn (Q3).
The format of the category is `RSYYYYQQ`, where YYYY is the year and QQ is the quarter of the start of the class. For example, winter - (Q1) or autumn - (Q3).

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +- **#announcements** - We write all announcements, as well as any important comments on the educational process, transfer of classes, new assignments to this channel. Any questions on the announcemen
- **#announcements** - We post all announcements, as well as any important comments on the educational process, rescheduling of classes, and new assignments to this channel. You can address your questions related to these announcements in the #questions channel. We recommend subscribing to notifications of new posts in this channel. This can be done in the channel's settings.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +- **#gratitude** - channel for thanks to students / lecturers. Mentors read it). Thanks are duplicated here sent through the RS APP application.
- **#gratitude** - channel to show your gratitude to students / lecturers. Mentors read it). 'Thank you' notes sent through the RS APP application are duplicated here.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +### What should I do before asking a chat question?
### What should I do before asking a question in a chat?

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +- Call the menu by right-clicking on the chat icon and select the "Change nickname" option.
- Right-click on the chat icon to see the menu and select the "Change nickname" option.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +Questions that are not suitable for special channels like # git-help / #padawanshelp / # live-coding, please ask in:
Questions that are not related to specific channels like # git-help / #padawanshelp / # live-coding, please ask in:

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +### In which channel is it better to thank for the help?
### In which channel it is better to thank for the help?

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +- Thanks can be sent through the RS APP application. In this case, it will remain in the recipient’s profile and will be duplicated in #gratitude
Gratitude can be sent through the RS APP application. In that case, it will remain in the recipient’s profile and will be duplicated in #gratitude channel.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/rs-school-chats.md
> +### Can I give links to torrents in the chat?
### Can I share links to torrents in the chat?

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +## Purposes of the first stage of training
## Goals of the first stage of training

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Students gaining basic knowledge of JS Basics
- Students gaining knowledge of JS Basics

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +## Schedule and assignment list
## Schedule and assignments list

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +   - Records of webinars and offline lectures can be found on our channel - https://www.youtube.com/user/therollingscopes
- Recordings of webinars ...

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +   - Records of an introductory session of past sets:
- Recordings of introductory sessions for previous classes:

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +  The video is better to watch at speeds of 1.25 or 1.5
It is better to watch the video at 1.25 or 1.5 speed.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +Offline Stream is a set of face-to-face lectures. For which we usually register up to 70 people. The quantity and material of the lecture depends on the teacher, but correlates with the material of w
Offline Stream is a set of face-to-face lectures for which we usually register up to 70 people. The number of slides and content of the lecture depends on the teacher, but they correlate with the material of webinars and lectures offered for self-study.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +Information about additional offline classes in your city we will post in the channel #announcements
We will post information about additional offline classes in your city in the channel #announcements

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +Participation is welcome but not required.
Participation is optional and everyone is welcome to attend.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +The schedule has lectures marked as "Self-study." It is expected that you have looked/look at the recordings of these lectures. It’s more convenient to watch at a speed of 1.25+
The schedule has lectures marked as "Self-study." It is expected that you watch those recordings. You can find it more convenient to watch them at a speed of 1.25+.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- The test consists of 45 questions per 100 points.
- The test has 45 questions and the maximum possible score is 100 points.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- The test is carried out 2 times. The maximum score of two tests is taken into account.
I was wondering why https://docs.rs.school/#/stage1 has conflicting information? I guess the https://docs.rs.school/#/stage1 is not up to date, right?

- The test is carried out 2 times. The maximum score of two tests is recorded.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- The test takes 24 hours.
- You can sit the test within 24 hours.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- It is expected that before the test you will be able to watch lectures on HTML/CSS (links are in the schedule), as well as go through tasks on codeacademy
- It is expected that before the test you watch lectures on HTML/CSS (links are in the schedule), as well as go through tasks on codeacademy

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +This is a short task whose description is not known in advance, and a limited time is allocated for execution (from 60 minutes to 48 hours).
This is a small task which is not given in advance, and has a short deadline for submission (from 60 minutes to 48 hours).

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +For example, on Monday at 21:00 everyone gets a link with a task, which takes 180 minutes to complete.
For example, on Monday at 21:00 everyone gets a link with a task description, and you are allowed 180 minutes to complete the task.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +    - merger
merging

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +Chapters that are desirable to read throughout the first stage:
You are advised to read the following chapters during the first stage:

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Alternative in English:
- Another resource in English:

PS: because it is not an alternative. The above links are in English as well.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Skip and try to complete the remaining tasks for the maximum score.
- Skip and try to get the maxim score for the remaining tasks.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Algorithmic tasks check unit tests, the score appears in RSAPP.
- Algorithmic tasks are run through unit tests, and the score appears in RSAPP.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Tests on git, html/css and js are checked automatically, the results are uploaded by the trainer to RSAPP, the score appears in RSAPP.
- Tests on git, html/css and js are checked automatically, and then trainers upload the results to RSAPP.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Task codeacademy/htmlacademy is checked automatically, the score appears in RSAPP.
- Codeacademy/htmlacademy task is checked automatically, and the score appears in RSAPP.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Assignment tasks are checked by Cross-check, and can also be checked by a mentor during an interview in stage # 2
- Layout tasks are cross-checked, and can also be reviewed by a mentor during stage # 2 interview.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Task Git & Markdown, GIt & HTML & CSS checked automatically
- Git & Markdown, GIt & HTML & CSS tasks checked automatically.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Code Jam "CSS Quick Draw" is checked automatically, the results are loaded into RSAPP, the score appears in RSAPP.
- Code Jam "CSS Quick Draw" is checked automatically, and the results are uploaded into RSAPP.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Sample assignment - https://github.com/SIARHEI-SMANTSAR/love-triangle
- Sample question - https://github.com/SIARHEI-SMANTSAR/love-triangle

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Estimates for these tasks are summed up in the overall score with a coefficient from 0.1 to 0.4 (maximum you can get 40 points for solving one problem)
- Each tasks has a coefficient from 0.1 to 0.4 (maximum you can get 40 points for solving one problem). The total is calculated by added all points together.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- We do not require solving all problems. In the last set, people who solved only 2-3 problems passed to the second stage of training.
- We do not require solving all problems. In the last cohort, students who solved only 2-3 problems got into the second stage of training.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- Schedule tasks ⇒ deductions. Think carefully before submitting someone else’s code to get 10 points.
- Plagiarism will get you expelled from the course. Think carefully before submitting someone else’s code to get 10 points.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- If during the interview you do not know how you solved the assignment you passed ⇒ there was a write-off ⇒ expulsion.
- If during the interview you cannot explain the solution of task that you submitted ⇒ that means you plagiarized ⇒ and you will get expelled.

2020-05-16 09:03 UTC, Munishkin commented on docs/en/stage1.md
> +- If during the interview you know how to solve the task, but you cannot solve the obviously simpler task ⇒ there was a cancellation ⇒ expulsion.
- If during the interview you know how to solve a task that you submitted, but you cannot solve an easier task ⇒ that means you plagiarized ⇒ and that means you will be expelled.

2020-06-08 08:59 UTC, dzmitry-varabei commented
@valentintur Thanks for the PR! Please apply all suggestions made by @Munishkin

2021-03-29 09:30 UTC, closed without merging