feat: add point about open repository folder
rolling-scopes-school/docs pull request #250
Opened 2022-09-27 18:48 UTC by ThorsAngerVaNeT

Add point about open repository folder after cloning repository

2022-10-19 20:54 UTC, auchynnikau requested changes

2022-10-19 20:54 UTC, auchynnikau commented on docs/private-repository.md
> +* Перейдите в папку склонированного репозитория
```suggestion
* Перейдите в папку склонированного репозитория:
```

2022-12-07 08:52 UTC, helenakrasnova approved these changes

2022-12-11 08:28 UTC, valerydluski approved these changes

2022-12-11 08:29 UTC, merged